## Numpy Practice 

In [2]:
import numpy as np

## Numpy is a numeric prthon 

## array is a collection of advanced list with sane on datatype that makes it more faster to compute

In [3]:
print(np.array([1,2,3,4,5])) #1D array # in the array the list is created inside the array function 

[1 2 3 4 5]


In [4]:
arr=np.array([[1,2,3,4],[5,6,7,8]]) #2D #in 2D the two list must be enclosed in a [[],[]] two square brackets

In [5]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


## Find - shape dimension & size datatype

In [6]:
arr.shape # shape gives rows & column structure of the array

(2, 4)

In [7]:
arr.size # Size gives numbers of elements inside the array

8

In [8]:
arr.ndim #ndim gives the  dimensions of the array 

2

## Print the type of the array

In [9]:
#type function provides info about the object of the array
type(arr) #1d,2d,3d the type() will still return ndarray because  all of them are objects of the same class:ndarray 

numpy.ndarray

## Print the data type 

In [10]:
arr.dtype #it gives what type of data is there inside the arry

dtype('int64')

## access the first 4 numbers from rows & columns [1,2,5,6]

In [11]:
arr[0:,0:2]

array([[1, 2],
       [5, 6]])

## access the last 4 numbers from the row & columns[3,4,7,8]

In [12]:
arr[0:,2:]

array([[3, 4],
       [7, 8]])

## access the middle 4 numbers from the row & columns [2,3,6,7] of the 2D list

In [13]:
arr[0:,1:3]

array([[2, 3],
       [6, 7]])

## Create Zero Matrix

In [14]:
arr1=np.zeros((2,4)) #inside the function write the tuple of size
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
arr1.dtype

dtype('float64')

In [16]:
#astype is used to change the (data type ) of the data in pandas & numpy
arr4=arr1.astype(int)
print(arr4)

[[0 0 0 0]
 [0 0 0 0]]


In [17]:
arr4.dtype

dtype('int64')

## Create a 2x4 array of ones

In [18]:
arr2=np.ones((2,4)) #in both zeros & ones data type is float 

In [19]:
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Create a 3X3 array filled with value 7

In [20]:
arr3=np.full((3,3),7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


## Generate 10 random numbers between 0 and 1

In [21]:
#to generate random numbers between a range of given number we use random.rand
#random.rand generates random numbers between 0 & 1 only 
print(np.random.rand(10))

[0.13619446 0.24363128 0.97845219 0.95105016 0.04479413 0.50679676
 0.33528562 0.84037285 0.55217843 0.74844191]


## Using arange Create numbers from 1 to 20

In [22]:
print(np.arange(1,21))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Create even numbers between 20 and 40

In [23]:
print(np.arange(20,41,2))

[20 22 24 26 28 30 32 34 36 38 40]


## Create 5 evenly spaced values between 3 and 4

In [24]:
#to create an evenly space values between the given range we use linspace
print(np.linspace(3,4,5))

[3.   3.25 3.5  3.75 4.  ]


## Indexing 

In [25]:
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##  first 4 elements [1,2,4,5]

In [26]:
arr5[0:2,0:2]

array([[1, 2],
       [4, 5]])

## access the 4 elements [2,3,5,6]

In [27]:
arr5[0:2,1:]

array([[2, 3],
       [5, 6]])

## access the 4 elements [4,5,7,8]

In [28]:
arr5[1:,0:2]

array([[4, 5],
       [7, 8]])

## access the 4 elements [5,6,8,9]

In [29]:
arr5[1:,1:]

array([[5, 6],
       [8, 9]])

## access the first vertical column 

In [30]:
arr5[:,0]

array([1, 4, 7])

## acces the first Horizontal column 

In [31]:
arr5[0,:]

array([1, 2, 3])

## Convert 1D to 2D Array

In [32]:
arr6=(np.arange(1,10))
print(arr6)
arr6=arr6.reshape(3,3)
print(arr6)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Looping through array

In [44]:
#lopping through the array means we get  all the elements separately 
arr7=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
for i in arr7:
    for j in i:
        print(j)
    



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


## Add 10 to Each Element

In [34]:
#Brodcasting=adding 10 to all the elements individually 
print(arr6+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


## Multiply Arrays

In [45]:
arr7=np.array([[1,2,3],[4,5,6]])
arr8=np.array([[1,2,3],[4,5,6]])
print(arr7*arr8)

[[ 1  4  9]
 [16 25 36]]


In [35]:
arr4 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr4*arr5)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [36]:
arr4 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr4@arr5)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Find mean, median, mode



In [53]:
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [54]:
mean=np.mean(arr)
print(mean)

30.0


In [55]:
median=np.median(arr)
print(median)

30.0


In [56]:
max=np.max(arr)
print(max)

50


In [57]:
min=np.min(arr)
print(min)

10


In [58]:
arr=np.array([12,7,12,45,23,7,7,89,23,45,12,56])
from scipy import stats 
print(stats.mode(arr))

ModeResult(mode=np.int64(7), count=np.int64(3))


 You have marks of students:
 marks = [45, 78, 90, 66, 88, 72, 59] Tasks:
 Convert to NumPy array
 Find average marks
 Find highest & lowest marks
 Find students scoring above average
 Add 5 grace marks to all students

In [73]:
marks=np.array([45, 78, 90, 66, 88, 72, 59])
print(marks)
average=print(np.mean(marks))
highest_marks=print(np.max(marks))
lowest_marks=print(np.min(marks))
grace=print(marks+5)
score_above_average=print(marks[marks>np.mean(marks)])

[45 78 90 66 88 72 59]
71.14285714285714
90
45
[50 83 95 71 93 77 64]
[78 90 88 72]


In [72]:
##filtering 
print(marks>np.mean(marks))
print(marks[marks>np.mean(marks)])

[False  True  True False  True  True False]
[78 90 88 72]


Temperature recorded for 7 days:

temps = [30, 32, 35, 31, 29, 40, 38] Tasks:
Find days with temperature > 35
Count number of hot days

In [93]:
temps=np.array([30,32,35,31,29,40,38])
print(temps)
hot_days=temps[temps>35]
print(hot_days)
#to count the numbers use the function len()
print(len(hot_days))


[30 32 35 31 29 40 38]
[40 38]
2


Employee salaries:

salary = [25000, 40000, 35000, 50000, 45000] Tasks:
Increase all salaries by 10%
Find employees earning > 40000

In [127]:
salary =np.array([25000, 40000, 35000, 50000, 45000])
print(salary)
salary_Inc=print(salary+salary*0.10)#original salary + original salary*0.10(incerement)
salary=print(salary[salary>40000])

[25000 40000 35000 50000 45000]
[27500. 44000. 38500. 55000. 49500.]
[50000 45000]


A grayscale image (3x3 pixels):

img = [[100, 150, 200], [50, 75, 125], [0, 25, 255]] Tasks:
Convert to NumPy array
Increase brightness by 20
Clip values to max 255

In [115]:
img =np.array([[100, 150, 200], [50, 75, 125], [0, 25, 255]])
print(img)

[[100 150 200]
 [ 50  75 125]
 [  0  25 255]]


In [121]:
bright=img+20
print(bright)

[[120 170 220]
 [ 70  95 145]
 [ 20  45 275]]


In [122]:
#clip {np.clip(img ,range)}
print(np.clip(bright,0,255))

[[120 170 220]
 [ 70  95 145]
 [ 20  45 255]]


Sales for 5 days:

sales = [200, 300, 250, 400, 350] Tasks:
Find total sales
Find day with highest sales
Find days where sales < 300

In [108]:
sales = np.array([200, 300, 250, 400, 350])
print(sales)

[200 300 250 400 350]


In [109]:
total=print(np.sum(sales))

1500


In [111]:
highest_sales=print(np.max(sales))

400


In [113]:
less_sales=print(sales[sales<300])

[200 250]


Scores:

scores = [55, 65, 75, 85, 95] Tasks:
Get students with grades ≥ 75
Replace scores < 60 with 60

In [114]:
scores =np.array( [55, 65, 75, 85, 95])
print(scores)

[55 65 75 85 95]


In [125]:
grades=(scores[scores>=75])
print(grades)

[75 85 95]


In [126]:
print(scores[scores<60],60)

[55] 60
